"""
Django settings for EduTecs project.
Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv  # <--- IMPORTANTE: Cargar dotenv

# Cargar variables del archivo .env (solo en local)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- SEGURIDAD: LEER SECRETOS DEL ENTORNO ---

# SECURITY WARNING: keep the secret key used in production secret!
# Lee la clave del .env o usa una por defecto SOLO para desarrollo local si falla
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-clave-default-para-dev')

# SECURITY WARNING: don't run with debug turned on in production!
# En Render pondrás DEBUG=False. En tu .env local pondrás DEBUG=True
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Permitir que Render sirva la app
ALLOWED_HOSTS = ['*']

# --- CONFIGURACIÓN DE CORS (SEGURIDAD) ---

# 1. Desactiva el permiso universal
CORS_ALLOW_ALL_ORIGINS = False 

# 2. Lista Blanca: Solo estos dominios pueden hablar con tu API
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",              # Tu Angular local
    "http://127.0.0.1:4200",              # Alternativa local
    "https://edutecs-frontend.vercel.app" # <--- TU FRONTEND REAL
]

# 3. Confianza CSRF para formularios seguros
CSRF_TRUSTED_ORIGINS = [
    "https://edutecs-frontend.vercel.app",
]

# Application definition
INSTALLED_APPS = [
    'jazzmin', # Admin Panel Theme
    'rest_framework',
    'tecnicas.apps.TecnicasConfig',
    'django_filters',
    'api.apps.ApiConfig',
    'corsheaders',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # CORS va primero
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # <--- WhiteNoise para estáticos en Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EduTecs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EduTecs.wsgi.application'

# --- BASE DE DATOS (POSTGRESQL / NEON) ---
DATABASES = {
    'default': dj_database_url.config(
        # Busca la variable DATABASE_URL en tu .env o en Render.
        # Si no la encuentra, usa un sqlite temporal (o puedes poner tu mysql local aquí como fallback)
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True # Importante para Neon Tech
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# --- REST FRAMEWORK CONFIG ---
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 6, # Ajustado a 6 para tu grilla en el frontend
    'MAX_PAGE_SIZE': 1000,
    'PAGE_SIZE_QUERY_PARAM': 'page_size', # Permite pedir ?page_size=100 en los selects
}

# --- JAZZMIN SETTINGS (ADMIN) ---
JAZZMIN_SETTINGS = {
    "site_title": " ",
    "site_header": " ",
    "site_brand": "Edutecs",
    "site_logo": "tecsup1.png",
    "login_logo": None,
    "login_logo_light": None,
    "site_logo_classes": "none",
    "site_icon": None,
    "welcome_sign": "Bienvenido al panel de administración - Edutecs",
    "copyright": "Acme Library Ltd",
    "user_avatar": None,
    "topmenu_links": [{"app": "books"}],
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
    "custom_links": {},
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-info",
    "navbar": "navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-lightblue",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "spacelab",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}

LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- ARCHIVOS ESTÁTICOS (WHITENOISE) ---
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'